<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config' => [
        // ⚠️ The HTTP client timeout MUST be higher than polling.timeout.
        // Telegram holds the connection open for polling.timeout seconds.
        // If the client cuts it before Telegram responds, cURL error 28 occurs.
        'timeout' => 60, // Increased to 60s for better buffer

        'polling' => [
            // How long Telegram holds the HTTP connection waiting for new updates.
            // Lower value (e.g., 20) is safer for flaky connections or restrictive ISPs.
            'timeout' => 20,
            'limit'   => 100,
        ],

        // Proxy support (useful for regions with restricted Telegram access, e.g. Ethiopia)
        // To enable, set TELEGRAM_PROXY in your .env, e.g.:
        //   TELEGRAM_PROXY=socks5://127.0.0.1:1080
        //   TELEGRAM_PROXY=http://user:pass@proxy.example.com:8080
        'client' => array_filter([
            'proxy' => env('TELEGRAM_PROXY'),
            'connect_timeout' => 10, // Timeout for initial connection
            'timeout' => 60, // Explicitly tell Guzzle to wait longer than the 20s polling
        ]),
    ],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
