<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use OwenIt\Auditing\Contracts\Auditable;

class PaymentTransaction extends Model implements Auditable
{
    use HasFactory, SoftDeletes, \OwenIt\Auditing\Auditable;

    protected $fillable = [
        'payment_id',
        'amount',
        'fine_paid',
        'is_gift',
        'payment_method',
        'reference_number',
        'paid_at',
        'recorded_by',
    ];

    protected function casts(): array
    {
        return [
            'amount' => 'decimal:2',
            'fine_paid' => 'decimal:2',
            'is_gift' => 'boolean',
            'paid_at' => 'datetime',
        ];
    }

    public function payment(): BelongsTo
    {
        return $this->belongsTo(Payment::class);
    }

    public function recordedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'recorded_by');
    }

    protected static function booted()
    {
        $recalculate = function ($transaction) {
            // Also rollback any credits generated by this transaction if it's being deleted
            if (! $transaction->exists) {
                MemberCredit::where('source_transaction_id', $transaction->id)->delete();
            }

            if (! $transaction->payment_id) {
                return;
            }

            // Using find instead of relationship directly just to be safe if eager loaded differently
            $obligation = Payment::find($transaction->payment_id);
            if (! $obligation) {
                return;
            }

            $totalPaid = PaymentTransaction::where('payment_id', $obligation->id)->sum('amount');
            $creditApplied = (float) MemberCreditApplication::where('payment_id', $obligation->id)->sum('amount_applied');
            $effectivePaid = (float) $totalPaid + $creditApplied;

            $obligation->amount_paid = min((float) $totalPaid, (float) $obligation->total_amount_due);

            if ($effectivePaid >= $obligation->total_amount_due) {
                $obligation->status = 'paid';
                if (! $obligation->paid_at) {
                    $obligation->paid_at = now();
                }
            } elseif ($effectivePaid > 0) {
                $obligation->status = 'partial';
                $obligation->paid_at = null;
            } else {
                $obligation->status = $obligation->fine_amount > 0 ? 'late' : 'pending';
                $obligation->paid_at = null;
            }

            $obligation->save();
        };

        static::created($recalculate);
        static::updated($recalculate);
        static::deleted($recalculate);
        static::restored($recalculate);
    }
}
